### ISSUE TITLE
Add session token cache

### ISSUE THREAD

**Issue by martinmicunda** [CoffeeAndCode/aws-auth-helper#2]
Hi,

I am using your plugin with serveless framework however I have situation when I want to deploy multiple lambda function over and over for testing purpose in 10 mins time period and I find to input `AWS MFA token` each time when I want to deploy something overkill. Is it possible to implement some kind of cache e.g. `AWS_SESSION_TOKEN` for 15-30 mins (I think the aws cli already does this automatically) to  avoid to type `AWS MFA token` in 10 mins time period? Thanks

**Comment by jonknapp** [comment]
Glad you found this project of use!

You are correct that the session info is currently not persisted between calls. I believe the AWS CLI handles this by storing a file in your `~/.aws` folder with the cached credentials and only re-asking for authorization if they fail. I'd like to avoid storing files on the user's machine if possible, but caching is a good idea.

You can also use the info passed back by `aws-auth-helper` for multiple calls, but the one example in the README does not show how to pull it off.  The session data returned is valid for X minutes (whatever the default for the call is) so you can store the results as environment variables and re-use them by making the call to serverless from the same terminal session without calling `aws-auth-helper` again.

That may look something like this:

```
eval `aws-auth-helper [aws-profile-name]`
serverless deploy

# ...
serverless deploy

# ...
serverless deploy
```

**Comment by martinmicunda** [comment]
hmm it doesn't seem to work for me.

I have simple `package.json`:

```json
{
  "name": "test",
  "scripts": {
    "sls": "serverless",
    "auth": "eval \"`aws-auth-helper dev`\"",
    "deploy": "sls deploy -v"
  },
  "devDependencies": {
    "serverless": "1.0.0-rc.2",
    "aws-auth-helper": "0.1.1"
  }
}
```

so I try to run `npm run auth` to input MFA token and then `npm run deploy` however I am getting `Acess Denied` error, I believe it's because the `npm run deploy` is not loading exporting env variables from `npm run auth` command.

**Comment by jonknapp** [comment]
Guessing it's an issue persisting the environment variables from the subshell call from NPM to your main terminal. You may have to change where you call `eval` so that the environment vars are set outside of the npm script call itself.

I'm not great at Bash at all, but maybe something like this:

```
eval `aws-auth-helper dev`
npm run deploy
```

I tried to make it work inside an npm script, but I ran into issues. Think it may be from the output from the npm command itself. I'm sure someone with stronger Bash-fu could figure it out though.
